### ISSUE TITLE
upgrade tika-core

### ISSUE THREAD

**Issue by reynoldsnlp** [reynoldsnlp/flair#1]
...to at least `1.20`

**Comment by mjbriggs** [comment]
If the updated tika dependencies cause a noSuchFieldError exception at run time, I recommend cleaning out both the maven repository and the /src/main/webapps/WEB-INF/lib folder and then recompiling. To clean out the maven repo, this [stackoverflow](https://stackoverflow.com/questions/7408545/how-do-you-clear-apache-mavens-cache) page provides an easy way to clean out your maven repo. After cleaning out these repos, you will need to download both the russian third party dependency and the old stanford tregex dependency. Both can be found in the readme.
