### ISSUE TITLE
Make Grammar constructions language-specific

### ISSUE THREAD

**Issue by reynoldsnlp** [reynoldsnlp/flair#10]

**Comment by reynoldsnlp** [comment]
Let's do this on the `russian` branch

**Comment by jhveem** [comment]
I would also add, hide grammar constructions for languages where they're not built in yet like Arabic.

**Comment by mjbriggs** [comment]
I have not done much work on this issue. In regards to grammar constructions being grammar specific, the only implementation has been hiding grammatical constructions for the Arabic branch. The front end makes use of gwt widgets, which is made up of xml files linked to java files. The client.presentation.widgets.sliderbundles package contains the different sliderbundles for German and English grammatical constructions. A sliderbundle represents the collection of grammatical constructions that appear on the left side of the search results page. These slider bundles are used in the RankerSettings widget which can be found in the client.presentation.widget package.
