### ISSUE TITLE
search on specific websites, possibly even curate a list of sites

### ISSUE THREAD

**Issue by reynoldsnlp** [reynoldsnlp/flair#22]

**Comment by jhveem** [comment]
For when/if this gets implemented, here is my working list of sites that seem to consistently provide good results for Arabic.

Aljazeera.net (news)
bbc.com/arabic (news)
Haybinyakzhan.blogspot.com (blog)
Arageek.com (blog)
Mawdoo3.com (encyclopedia style articles)
Hindawi.org (ebooks)

**Comment by mjbriggs** [comment]
I have not done any work on this issue.

**Comment by reynoldsnlp** [comment]
Here are some potentially good Russian websites:

http://klepa.ru/klep-news
https://read-ka.cofe.ru/
http://www.filipoc.ru/
http://unnaturalist.ru/
https://kvantik.com/
https://murzilka.org/izba-chitalnya/interesting/murzilka-i-aeroekspress/
https://www.bbc.com/russian
https://lenta.ru/

**Comment by reynoldsnlp** [comment]
http://help.bing.microsoft.com/#apex/18/en-US/10001/-1

> "site:" returns webpages that belong to the specified site. To focus on two or more domains, use a logical OR to group the domains. You can use site: to search for web domains, top level domains, and directories that are not more than two levels deep. You can also search for webpages that contain a specific search word on a site.

> To see webpages about heart disease from the BBC or CNN websites, type "heart disease" (site:bbc.co.uk OR site:cnn.com). To find webpages about the PC version of Halo on the Microsoft website, type site:www.microsoft.com/games/pc halo.

**Comment by reynoldsnlp** [comment]
@rkechols , as soon as we have a good foundation of grammar topics, let's make this feature a priority.

**Comment by rkechols** [comment]
Lists of specific websites to be searched can be created/edited in the file `src/main/java/com/flair/server/crawler/BingSearchAgent.java` on branch `russian2`
Currently there are lists for Russian and Arabic, using the lists given above.

I haven't gotten the Russian search to show any results from `klepa.ru/klep-news` nor `murzilka.org/izba-chitalnya/interesting/murzilka-i-aeroekspress` even when the search query is a direct quote copied from the front page.

**Comment by rkechols** [comment]
The UI now has a selection of searching only in curated domains vs any domain.
If a specific language has no list of domains, selecting `Curated Domains` sends an error message to the log and then behaves as `Any Domain` would.
