### ISSUE TITLE
Ability to request the next batch of results

### ISSUE THREAD

**Issue by jhveem** [reynoldsnlp/flair#23]
It would be nice if it were possible to request the next x search results. For example, if I request 10 sites, and none of them are quite what I'm looking for, it would be nice to just look for the next 10 instead of having to request 20 and reprocess the 10 I already know aren't going to work.

**Comment by mjbriggs** [comment]
I have not done any work on this issue.

**Comment by rkechols** [comment]
Functionality complete on branch `page-results`
Needs to be merged into `master`

**Comment by rkechols** [comment]
Merged into `master`
