### ISSUE TITLE
server appears to be down

### ISSUE THREAD

**Issue by jhveem** [reynoldsnlp/flair#28]
This may be planned maintenance or something, but when I run a search in any language I get the following errors.

Failed to load resource: the server responded with a status of 404 ()

Failed to load resource: the server responded with a status of 500 ()

SEVERE:  Couldn't begin web search operation. Exception: com.google.gwt.user.client.rpc.StatusCodeException: 500  The call failed on the server; see server log for details
Obb @ flair-0.js:3041
Hhc @ flair-0.js:2862
Ghc @ flair-0.js:2070
Ihc @ flair-0.js:1836
Tz @ flair-0.js:2844
Pz @ flair-0.js:1639
Tl @ flair-0.js:3040
Wc @ flair-0.js:3035
rib @ flair-0.js:2974
LS @ flair-0.js:2259
YS @ flair-0.js:3041
(anonymous) @ flair-0.js:2110
xJ @ flair-0.js:1445
AJ @ flair-0.js:2750
(anonymous) @ flair-0.js:2100

**Comment by reynoldsnlp** [comment]
@jhveem , we've had issues with the installation on the server. We're working right now to get it working with a docker container.

**Comment by mjbriggs** [comment]
I have set up a docker container that runs FLAIR just fine. What prevented from working on my mac machine was that docker installed itself with limits on how much RAM and swap space that prevented language models from being loaded when run. If you run FLAIR in docker and it seems to hang on the parser load operation, check if there are any limits on docker's memory access and change it.
