### ISSUE TITLE
Decide what Russian grammatical constructions to incorporate

### ISSUE THREAD

**Issue by rkechols** [reynoldsnlp/flair#30]
We need to decide which grammatical constructions for the project to recognize and report.

**Comment by reynoldsnlp** [comment]
@rkechols Let's start with the following for word-based features

Noun cases:
- Nominative
- Accusative
- Genitive
- Prepositional
- Dative
- Instrumental

Adjective cases:
- (same cases as listed above)

Prepositions:
- (same cases as listed above)

Verb tenses:
- Past
- Present/Future

Participles:
- Present active
- Present passive
- Past active
- Past passive

Particles:
- ли
- бы

**Comment by reynoldsnlp** [comment]
Each of these can simply be based on the normalized count of tokens with the target tags.
