### ISSUE TITLE
Add names to constructions for conjugation classes

### ISSUE THREAD

**Issue by rkechols** [reynoldsnlp/flair#47]
On the branch `russian2` in the file `src/main/java/com/flair/client/localization/resources/strings-en-constructions.tsv`, lines 688 through 741 need user-facing info about conjugation classes.
- Rows that start with `_gram-name_` need a short name describing the conjugation class
- Rows that start with `_gram-helpText_` need a short description and/or examples

These values should be placed in the 3rd column (after the 2nd `\t` character)

**Comment by reynoldsnlp** [comment]
First attempt made in 249b38897107e2321c51c24edafa94ca507660c3. May need to rethink how closely to follow Zalizniak, since not all of the classes are well-motivated for pedagogical purposes.
